config/routes.rb
Rails.application.routes.draw do
  get 'paypal/checkout' => 'bookings#paypal_checkout'
  get 'bookings/paypal' => 'bookings#payment_save', as: :payment_save
  namespace :cms do
    get '/watting_bookings' => 'bookings#watting_bookings', as: :watting_bookings
    resources :allow_ip_addresses
    post '/allow_ip_addresses' => 'allow_ip_addresses#create', as: :create_allow_ip
    resources :image_room_tops, only: [:index, :update]
    put '/cms/update_image_room_tops' => 'image_room_tops#update', as: :update_image_room_tops
    resources :room_cannot_chooses
    root 'sessions#new'
    resources :services
    resources :bookings do
      resources :booking_services
    end
    get '/booking_services' => 'booking_services#index', as: :all_booking_services
    delete 'room_cannot_chooses/all/delete_all' => 'room_cannot_chooses#destroy_all', as: :room_cannot_chooses_all
    post '/bookings_services/:id' => 'booking_services#update', as: :update_booking_services
    resources :users
    resources :sessions
    resources :rooms
    resources :customers
    resources :top_images
    get 'histories/bookings' => 'bookings#history_index'
    get 'histories/bookings/:id' => 'bookings#histories'
    get 'bookings/:id/bill' => 'bookings#bill', as: :room_bill
    get 'csv_bill', to: 'bookings#csv_bills', as: :foo_export
    get 'customers/:id/bookings' => 'customers#bookings'
    get 'top_image_chooses' => 'top_images#edit_top_image_chooseds'
    put 'top_images_chooses' => 'top_images#update_top_image_chooses', as: :update_top_image_chooses
    get 'allrooms/bookings' => 'rooms#all_bookings'
    get 'rooms/:id/bookings' => 'rooms#bookings'
    get 'bookings/:id/new_services' => 'bookings#new_services', as: :booking_new_services
    post 'bookings/:booking_id/create_services/:service_id' => 'bookings#create_services', as: :booking_services
    put 'bookings/:booking_id/services' => 'booking_services#paid_all', as: :paid_all_services
    get 'all_rooms/bookings' => 'rooms#index_bookings', as: :bookings_all_rooms
    put '/booking/:id/booking_pay' => 'bookings#pay', as: :booking_pay
    get '/admin_find_rooms' => 'rooms#admin_find', as: :admin_find_rooms
    get '/employee_find_rooms' => 'rooms#employee_find_rooms', as: :employee_find_rooms
    get '/bookings_services_watting' => 'booking_services#waitting', as: :booking_services_waitting
    resources :employees
    post 'users/:id/changepassword' => 'users#changepassword', as: :changepassword
    post 'users/:id/update_avatar' => 'users#update_avatar', as: :update_avatar
    delete 'sessions#logout' => 'sessions#account_logout_out', as: :logout
    put 'booking_services/chooseds/pay' => 'booking_services#pay_chooseds', as: :booking_services_pay_chooseds
    put 'booking_services/invoice' => 'booking_services#invoice', as: :booking_services_invoice
    put 'bookings_invoice/:id' => 'bookings#invoice', as: :booking_invoice
    resources :revenues
  end

    get 'index' => 'homepages#index'
    get '/homepages/event' => 'homepages#event', as: :home_event
    resources :bookings, only: %w[new create show]
    resources :rooms, only: %w[show index]
    resources :customers
    root 'homepages#home'
    get '/booking/verify/success' => 'booking_verifies#success'
    get 'bookings/:id/watting_verify' => 'booking_verifies#watting_verify', as: :booking_watting_verify
    resources :booking_verifies, only: :edit
    post 'create_booking_with_payment' => 'bookings#create_booking_with_payment', as: :create_booking_with_payment
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
  def home
    @top_images = TopImage.where("top_choosed_number > ?", 0)
    @rooms = Room.joins(:image_room_tops).order('image_room_tops.image_room_top_number ASC')
  end

  def index
  end

  def booking
    save_with_paypal_payment
  end

  def save_with_paypal_payment
    ppr = PayPal::Recurring.new(
      token: params[:token],
      payer_id: params[:PayerID],
      description: 'a',
      amount: Room.find(1).price,
      currency: 'USD'
      )
    response = ppr.request_payment
    if response.errors.present?
      raise response.errors.inspect
    else
    end
  end

  def help
  end

  def paypal_checkout
    @room = Room.find(params[:room_id])
    ppr = PayPal::Recurring.new(
      :return_url => paypal_booking_url(a: 1),
      cancel_url: root_url,
      description: @room.name,
      amount: @room.price,
      currency: "USD"
      )
    response = ppr.checkout
    if response.valid?
      redirect_to response.checkout_url
    else
      raise response.errors.inspect
    end
  end

  def event
  end
end

app/helpers/homepages_helper.rb
module HomepagesHelper
end

app/views/homepages/event.html.erb
asdsadsad

app/views/homepages/home.html.erb
<!DOCTYPE html>
<html>
  <title></title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
    body,h1,h2,h3,h4,h5,h6 {font-family: "Raleway", Arial, Helvetica, sans-serif}
  </style>
  <body class="w3-light-grey">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <% if @top_images.present? %>
        <% @top_images.each do |image| %>
        <div class="item <%='active' if image.top_choosed_number == 1%>">
          <img src="<%=image.top_icon.url%>" alt="Los Angeles" style="min-width:1000px; max-height: 500px;" width="1500" height="800">
          <div class="carousel-caption">
            <h3><%= image.title %></h3>
            <input type="" id="search_room" style="height: 0px;width: 0px;overflow:hidden;">
            <p><%= image.content %></p>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
      </a>
    </div>
    <!-- </div> -->
    </header>
    <!-- Page content -->
    <div id='' class="w3-content" style="max-width:1532px;">
      <div class="w3-container w3-margin-top" id="rooms">
        <h3>Rooms</h3>
        <p >Make yourself at home is our slogan. We offer the best beds in the industry. Sleep well and rest well.</p>
      </div>
      <form action="/rooms" onsubmit="return must_type_depart()">
        <div class="w3-row-padding">
          <div class="w3-col m3">
            <label><i class="fa fa-calendar-o"></i> Check In(*)</label>
            <input name='check_in' id="checkIn" class="w3-input w3-border check_in" type="date" min="<%=Time.zone.now.strftime('%Y-%m-%d')%>" value="<%= (Time.zone.now + 7.hour).strftime('%Y-%m-%d')%>" onchange="updatedate();">
          </div>
          <div class="w3-col m3">
            <label><i class="fa fa-calendar-o"></i> Check Out(*)</label>
            <input name='check_out' id="checkOut" class="w3-input w3-border check_out" type="date" min="<%=Time.zone.now.strftime('%Y-%m-%d')%>" value="<%= (Time.zone.now + 7.hour).strftime('%Y-%m-%d')%>">
          </div>
          <div class="w3-col m2">
            <label><i class="fa fa-male"></i> Adults</label>
            <input name='adults' value='1' min='1' class="w3-input w3-border" type="number" placeholder="Adults">
          </div>
          <div class="w3-col m2">
            <label><i class="fa fa-child"></i>Childrens</label>
            <input value="0", min="0" name='childrens' class="w3-input w3-border" type="number" placeholder="Childrens">
          </div>
          <div class="w3-col m2">
            <label><i class="fa fa-search" ></i> Search</label>
            <button type="submit" class="w3-button w3-block w3-black search_room">Search</button>
          </div>
        </div>
      </form>
      <!-- <div class="w3-row-padding w3-padding-16"> -->
      <div class="w3-row-padding w3-padding-16">
        <% if @rooms.present? %>
          <% @rooms.each do |room| %>
            <div class="w3-third w3-margin-bottom">
              <img src="<%=room.room_icon.thumb.url%>" alt="Norway" style="width:100%; height: 40%;">
              <div class="w3-container w3-white">
                <h3>Single Room</h3>
                <h6 class="w3-opacity">From $<%=room.price%></h6>
                <p>Single bed</p>
                <p>15m<sup>2</sup></p>
                <p class="w3-large"><i class="fa fa-bath"></i> <i class="fa fa-phone"></i> <i class="fa fa-wifi"></i></p>
                <button class="w3-button w3-block w3-black w3-margin-bottom">Choose Room</button>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      </div>
      <div class="w3-row-padding" id="about">
        <div class="w3-col l4 m7">
          <h3>About</h3>
          <h6>Our hotel is one of a kind. It is truely amazing. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam.</h6>
        </div>
        <div class="w3-col l8 m5">
          <a href="https://www.google.com/maps/place/Hoi+An+Beach+Resort/@15.8964181,108.3650807,17z/data=!3m1!4b1!4m5!3m4!1s0x31420d970efaa355:0x9e3cb85ef42337d!8m2!3d15.896413!4d108.3672748" target="_blank">
            <div id="map" style="width:100%;height:500px"></div>
          </a>
        </div>
      </div>
      <div class="w3-row w3-large w3-center" style="margin:32px 0">
        <div class="w3-third"><i class="fa fa-map-marker w3-text-red"></i> 1, Cua Dai, Hoi An</div>
        <div class="w3-third"><i class="fa fa-phone w3-text-red"></i> Phone: +84 1206146039</div>
        <div class="w3-third"><i class="fa fa-envelope w3-text-red"></i> Email: h0977534303@gmail.com</div>
      </div>
     <!--  <div class="w3-panel w3-red w3-leftbar w3-padding-32">
        <h6><i class="fa fa-info w3-deep-orange w3-padding w3-margin-right"></i> On demand, we can offer playstation, babycall, children care, dog equipment, etc.</h6>
      </div> -->
      <!-- <div class="w3-container">
        <h3>Our Hotels</h3>
        <h6>You can find our hotels anywhere in the world:</h6>
      </div>
      <div class="w3-row-padding w3-padding-16 w3-text-white w3-large">
        <div class="w3-half w3-margin-bottom">
          <div class="w3-display-container">
            <img src="/w3images/cinqueterre.jpg" alt="Cinque Terre" style="width:100%">
            <span class="w3-display-bottomleft w3-padding">Cinque Terre</span>
          </div>
        </div>
        <div class="w3-half">
          <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half w3-margin-bottom">
              <div class="w3-display-container">
                <img src="/w3images/newyork2.jpg" alt="New York" style="width:100%">
                <span class="w3-display-bottomleft w3-padding">New York</span>
              </div>
            </div>
            <div class="w3-half w3-margin-bottom">
              <div class="w3-display-container">
                <img src="/w3images/sanfran.jpg" alt="San Francisco" style="width:100%">
                <span class="w3-display-bottomleft w3-padding">San Francisco</span>
              </div>
            </div>
          </div> -->
          <!-- <div class="w3-row-padding" style="margin:0 -16px">
            <div class="w3-half w3-margin-bottom">
              <div class="w3-display-container">
                <img src="/w3images/pisa.jpg" alt="Pisa" style="width:100%">
                <span class="w3-display-bottomleft w3-padding">Pisa</span>
              </div>
            </div>
            <div class="w3-half w3-margin-bottom">
              <div class="w3-display-container">
                <img src="/w3images/paris.jpg" alt="Paris" style="width:100%">
                <span class="w3-display-bottomleft w3-padding">Paris</span>
              </div>
            </div>
          </div> -->
       <!--  </div>
      </div> -->
      <div class="w3-container w3-padding-32 w3-black w3-opacity w3-card-2 w3-hover-opacity-off" style="margin:32px 0;">
        <!-- <h2>Get the best offers first!</h2> -->
        <!-- <p>Join our newsletter.</p> -->
        <!-- <label>E-mail</label> -->
        <!-- <input class="w3-input w3-border" type="text" placeholder="Your Email address"> -->
        <!-- <button type="button" class="w3-button w3-red w3-margin-top">Subscribe</button> -->
      </div>
      <div class="w3-container" id="contact">
        <h2>Contact</h2>
        <p>If you have any questions, do not hesitate to ask them.</p>
        <i class="fa fa-map-marker w3-text-red" style="width:30px"></i> Hoi An<br>
        <i class="fa fa-phone w3-text-red" style="width:30px"></i> Phone: +84 1206146039<br>
        <i class="fa fa-envelope w3-text-red" style="width:30px"> </i> Email: h0977534303@gmail.com<br>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Name" required name="Name"></p>
          <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Email" required name="Email"></p>
          <p><input class="w3-input w3-padding-16 w3-border" type="text" placeholder="Message" required name="Message"></p>
          <p><button class="w3-button w3-black w3-padding-large" type="submit">SEND MESSAGE</button></p>
        </form>
      </div>
      <!-- End page content -->
    </div>
    <!-- Add Google Maps -->
    <script>
      function myMap() {
      var mapCanvas = document.getElementById("map");
      var myCenter = new google.maps.LatLng(15.8964181,108.3650807);
      var mapOptions = {center: myCenter, zoom: 15};
      var map = new google.maps.Map(mapCanvas,mapOptions);
      var marker = new google.maps.Marker({
      position: myCenter,
      animation: google.maps.Animation.BOUNCE
      });
      marker.setMap(map);
      }

      $(document).ready(function() {
        $("#booknow").on("click", function( e ) {
          e.preventDefault();
          $("body, html").animate({
            scrollTop: $( $(this).attr('href') ).offset().top
          }, 600);
        });
      });

       function updatedate() {
        var firstdate = document.getElementById("checkIn").value;
        document.getElementById("checkOut").value = "";
        document.getElementById("checkOut").setAttribute("min",firstdate);
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBi6hH_CRiZzGj9BkK3pQjuZ1o6uFTIzgQ&callback=myMap"></script>
  </body>
</html>

app/views/homepages/index.html.erb
<%= link_to image_tag("https://www.sandbox.paypal.com/en_US/i/btn/btn_xpressCheckout.gif"), paypal_checkout_path(room_id: 1) %>