config/routes.rb
Rails.application.routes.draw do
  get 'paypal/checkout' => 'bookings#paypal_checkout'
  get 'bookings/paypal' => 'bookings#payment_save', as: :payment_save
  namespace :cms do
    get '/watting_bookings' => 'bookings#watting_bookings', as: :watting_bookings
    resources :allow_ip_addresses
    post '/allow_ip_addresses' => 'allow_ip_addresses#create', as: :create_allow_ip
    resources :image_room_tops, only: [:index, :update]
    put '/cms/update_image_room_tops' => 'image_room_tops#update', as: :update_image_room_tops
    resources :room_cannot_chooses
    root 'sessions#new'
    resources :services
    resources :bookings do
      resources :booking_services
    end
    get '/booking_services' => 'booking_services#index', as: :all_booking_services
    delete 'room_cannot_chooses/all/delete_all' => 'room_cannot_chooses#destroy_all', as: :room_cannot_chooses_all
    post '/bookings_services/:id' => 'booking_services#update', as: :update_booking_services
    resources :users
    resources :sessions
    resources :rooms
    resources :customers
    resources :top_images
    get 'histories/bookings' => 'bookings#history_index'
    get 'histories/bookings/:id' => 'bookings#histories'
    get 'bookings/:id/bill' => 'bookings#bill', as: :room_bill
    get 'csv_bill', to: 'bookings#csv_bills', as: :foo_export
    get 'customers/:id/bookings' => 'customers#bookings'
    get 'top_image_chooses' => 'top_images#edit_top_image_chooseds'
    put 'top_images_chooses' => 'top_images#update_top_image_chooses', as: :update_top_image_chooses
    get 'allrooms/bookings' => 'rooms#all_bookings'
    get 'rooms/:id/bookings' => 'rooms#bookings'
    get 'bookings/:id/new_services' => 'bookings#new_services', as: :booking_new_services
    post 'bookings/:booking_id/create_services/:service_id' => 'bookings#create_services', as: :booking_services
    put 'bookings/:booking_id/services' => 'booking_services#paid_all', as: :paid_all_services
    get 'all_rooms/bookings' => 'rooms#index_bookings', as: :bookings_all_rooms
    put '/booking/:id/booking_pay' => 'bookings#pay', as: :booking_pay
    get '/admin_find_rooms' => 'rooms#admin_find', as: :admin_find_rooms
    get '/employee_find_rooms' => 'rooms#employee_find_rooms', as: :employee_find_rooms
    get '/bookings_services_watting' => 'booking_services#waitting', as: :booking_services_waitting
    resources :employees
    post 'users/:id/changepassword' => 'users#changepassword', as: :changepassword
    post 'users/:id/update_avatar' => 'users#update_avatar', as: :update_avatar
    delete 'sessions#logout' => 'sessions#account_logout_out', as: :logout
    put 'booking_services/chooseds/pay' => 'booking_services#pay_chooseds', as: :booking_services_pay_chooseds
    put 'booking_services/invoice' => 'booking_services#invoice', as: :booking_services_invoice
    put 'bookings_invoice/:id' => 'bookings#invoice', as: :booking_invoice
    resources :revenues
  end

    get 'index' => 'homepages#index'
    get '/homepages/event' => 'homepages#event', as: :home_event
    resources :bookings, only: %w[new create show]
    resources :rooms, only: %w[show index]
    resources :customers
    root 'homepages#home'
    get '/booking/verify/success' => 'booking_verifies#success'
    get 'bookings/:id/watting_verify' => 'booking_verifies#watting_verify', as: :booking_watting_verify
    resources :booking_verifies, only: :edit
    post 'create_booking_with_payment' => 'bookings#create_booking_with_payment', as: :create_booking_with_payment
end

app/controllers/cms/allow_ip_addresses_controller.rb
class Cms::AllowIpAddressesController < Cms::ApplicationController
  before_action :check_admin
  def new
    @allow_ip_address = AllowAddressIp.new
  end

  def create
    AllowAddressIp.create allow_ip_address_params
    redirect_to cms_allow_ip_addresses_url
  end

  def destroy
    AllowAddressIp.find(params[:id]).delete
    redirect_to cms_allow_ip_addresses_url
  end

  def allow_ip_address_params
    params.require(:allow_address_ip).permit(:ip_address)
  end
end

app/controllers/cms/application_controller.rb
class Cms::ApplicationController < ApplicationController
  before_filter :block_ip_addresses
  before_action :check_if_valid_user_login
  def check_if_valid_user_login
    # it would be improve in future
    if controller_name != 'sessions'
      redirect_to cms_root_url if current_user.blank? || (current_user.user_type != 'Admin' && current_user.user_type != 'Employee')
    end
  end

  def block_ip_addresses
    allow_ip_addresses = AllowAddressIp.pluck(:ip_address)
    head :unauthorized if allow_ip_addresses.exclude?(current_ip_address)
  end

  def current_ip_address
    request.env['HTTP_X_REAL_IP'] || request.env['REMOTE_ADDR']
  end

  def check_admin
    redirect_to cms_root_path if current_user.user_type != 'Admin'
  end

  def service_prices booking
    total_prices = 0
    booking_services = BookingService.where(booking_id: booking.id, pay: :paid).where.not(status: :cancel)
    booking_services.each do |booking_service|
      total_prices = total_prices + booking_service.number*booking_service.price
    end
    total_prices
  end

  def get_date_incomes_date start_date
    dates = []
    start_date = Time.zone.now if start_date.blank?
    dates << (start_date.to_date - 2.year).strftime('%Y')
    dates << (start_date.to_date - 1.year).strftime('%Y')
    dates << start_date.to_date.strftime('%Y')
    dates
  end
end

app/controllers/cms/booking_services_controller.rb
class Cms::BookingServicesController < Cms::ApplicationController
  def new
    @booking_service = BookingService.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
  end

  def index
    @booking_services = BookingService.all
    @booking_services = @booking_services.order(:created_at).includes({booking: :room}, :service).page(params[:page]).per(10)
  end

  def update
    @booking_service = BookingService.find(params[:id])
    if booking_service_params[:commit].present?
      @booking_service.booked if params[:commit] == 'booked' && @booking_service.may_booked?
      @booking_service.cancel if params[:commit] == 'cancel' && @booking_service.may_cancel?
      @booking_service.paid   if params[:commit] == 'paid'   && @booking_service.may_paid?
      @booking_service.save
      redirect_to cms_booking_new_services_url(@booking_service.booking_id)
    end
  end

  def waitting
    @booking_services = BookingService.where(status: :watting).order(time: :asc).includes({booking: :room}, :service).page(params[:page]).per(10)
    render :index
  end

  def paid_all
    BookingService.paid_all(params[:booking_id])
    redirect_to cms_booking_new_services_url(params[:booking_id])
  end

  def pay_chooseds
    BookingService.where(id: params[:booking_service_ids]).update_all(pay: :paid)
    redirect_to cms_booking_new_services_path(params[:booking_id])
  end

  def invoice
    booking_services = BookingService.where(id: params['booking_service_ids'])
    if booking_services.present?
      items = []
      totlal_prices = 0
      booking_services.each do |booking_service|
        service = booking_service.service
        amount_after_tax = booking_service.price*booking_service.number
        item = InvoicePrinter::Document::Item.new(
          name: service.name,
          quantity: booking_service.number,
          price: booking_service.price*85/100,
          amount: '$ ' + (amount_after_tax*85/100).to_s
        )
        totlal_prices = totlal_prices + amount_after_tax
        items<<item
      end
      booking = booking_services.first.booking
      customer = booking.customer

      invoice = InvoicePrinter::Document.new(
        number: booking.id,
        provider_name: 'My Hotel',
        provider_tax_id: '56565656',
        provider_tax_id2: '465454',
        provider_street: 'Cua Dai',
        provider_street_number: '1',
        provider_city: 'Hoi An',
        purchaser_name: customer.name,
        purchaser_street: customer.street,
        purchaser_street_number: customer.number_street,
        purchaser_city: customer.city,
        purchaser_postcode: customer.postcode,
        due_date: (Time.zone.now + 7.hour).strftime('%Y-%m-%d %I:%M:%S %p'),
        subtotal: totlal_prices*85/100,
        tax: totlal_prices*10/100,
        tax2: totlal_prices*5/100,
        total: '$ ' + totlal_prices.to_s,
        items: items,
        note: 'A note...'
      )

      respond_to do |format|
        format.pdf {
          @pdf = InvoicePrinter.render(
            document: invoice
          )
          send_data @pdf, type: 'application/pdf', disposition: 'inline'
        }
      end
    else
      redirect_to cms_booking_new_services_path(params[:booking_id])
    end
  end

  def edit
    @booking_service = BookingService.find(params[:id])
  end

  def destroy
    BookingService.find(params[:id]).delete
  end

  def booking_service_params
    params.permit(:commit)
  end
end

app/controllers/cms/customers_controller.rb
class Cms::CustomersController < Cms::ApplicationController
  def index
    @customers = Customer.all
    @customers = @customers.where(email: params[:email]) if params[:email].present?
    @customers = @customers.where(country: params[:country]) if params[:country].present?
    @customers = @customers.where(postcode: params[:postcode]) if params[:postcode].present?
    @customers = @customers.page(params[:page]).per(25)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def bookings
    @customer = Customer.find(params[:id])
    @bookings = @customer.bookings.order(:created_at).page(params[:page]).per(10)
  end
end

app/controllers/cms/employees_controller.rb
class Cms::EmployeesController < Cms::ApplicationController
  def index
    @employees = Employee.all
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/cms/image_room_tops_controller.rb
class Cms::ImageRoomTopsController < Cms::ApplicationController
  before_action :init_record, :check_valid_params, only: :update

  def index
    @image_room_tops = ImageRoomTop.order(:image_room_top_number).all
  end

  def update
    if flash[:errors].blank?
      ImageRoomTop.update_rooms(image_room_top_params)
    end
    redirect_to cms_image_room_tops_url
  end

  def init_record
    ImageRoomTop.init_record
  end

  def check_valid_params
    flash[:errors] = ImageRoomTop.check_valid_params image_room_top_params
  end

  def image_room_top_params
    params.require(:image_room_tops).map {|a| a.permit(:image_room_top_number, :room_id)}
  end
end

app/controllers/cms/revenues_controller.rb
class Cms::RevenuesController < Cms::ApplicationController
  def index
    current_month = Time.zone.now.month
    current_year = Time.zone.now.year
    @dates_data = get_date_incomes_date(params['start_date'])
    @last_in_comes = Booking.get_last_in_comes(params['start_date'])
    @current_in_comes = Booking.get_current_in_comes(params['start_date'])
  end
end

app/controllers/cms/room_cannot_chooses_controller.rb
class Cms::RoomCannotChoosesController < Cms::ApplicationController
  before_action :check_valid_params, only: :create
  def update
  end

  def create
    @room_cannot_choose = RoomCannotChoose.new room_params
    if flash[:errors].blank?
      @room_cannot_choose.save
      flash[:success] = "Create success"
      redirect_to cms_room_cannot_chooses_url
    else
      @room_cannot_chooses = RoomCannotChoose.all
      render :index
    end
  end

  def index
    @room_cannot_chooses = RoomCannotChoose.all
  end

  def destroy
    RoomCannotChoose.find(params[:id]).delete
    redirect_to cms_room_cannot_chooses_url
  end

  def destroy_all
    RoomCannotChoose.delete_all
    redirect_to cms_room_cannot_chooses_url
  end

  def check_valid_params
    flash[:errors] = RoomCannotChoose.check_valid_params(room_params)
  end

  def room_params
    params.require(:room).permit(:room_id, :from_date, :to_date)
  end
end

app/controllers/cms/rooms_controller.rb
class Cms::RoomsController < Cms::ApplicationController
  before_action :check_admin, only:[:new, :create, :edit, :update, :destroy]
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to cms_rooms_path(id: @room.id)
      flash[:success] = "New Room was created"
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      redirect_to cms_rooms_path(id: @room.id)
      flash[:success] = "Update success"
    else
      redirect_to cms_rooms_path
      flash[:error] = "update fail"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def index
    if params[:check_in].present? && params[:check_out].present? || params[:booking_edit].present?
      @rooms = Room.get_emptys(params[:check_in], params[:check_out])      if params[:empty].present? || params[:booking_edit].present?
      @rooms = Room.get_are_usings(params[:check_in], params[:check_out])  if params[:in_use].present?
    else
      @rooms = Room.all
    end
    if params[:price].present?
      @rooms = @rooms.order(:price)                              if params[:price] == 1
      @rooms = @rooms.order(price: :desc)                        if params[:price] == -1
    end
    @rooms = @rooms.where("adults > ?", params[:adults])         if params[:adults].present?
    @rooms = @rooms.where("childrens > ?", params[:childrens]) if params[:childrens].present?
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def admin_find
    @rooms = Room.where(name: params[:name])
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    @rooms = @rooms.page(params[:page]).per(10)
    render 'index'
  end

  def employee_find_rooms
    @rooms = Room.get_emptys(params[:check_in], params[:check_out])
    @rooms = @rooms.where("adults >= ?", params[:adults]) if params[:adults].present?
    @rooms = @rooms.where("childrens >= ?", params[:childrens]) if params[:childrens].present?
    @number = @rooms.count
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    render 'index'
  end

  def bookings
    @room = Room.find(params[:id])
    @bookings = @room.bookings.where("status != ? AND verified IS ?", 'watting', true)
  end

  def index_bookings
    if params[:check_in].present? && params[:check_out].present?
      @rooms = Room.get_emptys(params[:check_in], params[:check_out])
    else
      @rooms = Room.all
    end
    @rooms = @rooms.where("adults > ?", params[:adults])         if params[:adults].present? && @rooms.present?
    @rooms = @rooms.where("childrens > ?", params[:childrens]) if params[:childrens].present? && @rooms.present?
    @rooms = @rooms.includes(:bookings) if @rooms.present?
    # @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    # @rooms = Room.all.includes(:bookings)
  end

  def all_bookings
    @rooms = Room.includes(:bookings).all
  end

  def destroy
    room = Room.find(params[:id])
    if room.destroy
      redirect_to cms_rooms_path
    end
  end

  private

    def room_params
      params.require(:room).permit(:id, :name, :room_type, :adults, :childrens, :price, :room_icon)
    end
end

app/controllers/cms/sessions_controller.rb
class Cms::SessionsController < Cms::ApplicationController
  def new
  end

  def create
    user = User.find_by(email: login_params[:email])
    if user.present? && user.password == login_params[:password]
      init_session(user)
      redirect_to cms_root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to cms_root_path
  end

  def account_logout_out
    logout
    redirect_to cms_root_path
  end

  def login_params
    params.permit(:email, :password)
  end
end

app/helpers/cms/allow_ip_addresses_helper.rb
module Cms::AllowIpAddressesHelper
end

app/helpers/cms/booking_services_helper.rb
module Cms::BookingServicesHelper
  STATUS_COLOR = {'watting'   => '#00FFFF',
                  'booked'  => '#00FF00',
                  'cancel' => '#FF4500'
                  }

  def may_pay_all? booking_id
    booking_service = BookingService.where(booking_id: booking_id, pay: 'unpaid').limit(1)
    booking_service.present? ? true : false
  end
end

app/helpers/cms/bookings_helper.rb
module Cms::BookingsHelper
  STATUS_COLOR = {  'watting'  => 'yellow',
                    'cancel'   => '#f00',
                    'accepted' => '#48D1CC',
                    'in_use'   => '#0f0',
                    'finished' => '#FFA500'
                    }.freeze
  def pay_link_to booking
    total_price = (((@booking.check_out - @booking.check_in)/1.day.to_i + 1).to_i)*(@booking.price.to_i)
    if booking.total_payed == nil || booking.total_payed < total_price
      link_to 'paid', cms_booking_pay_path(booking.id), class: 'btn btn-success btn-xs', method: :put
    elsif booking.total_payed > total_price
      link_to 'change', cms_booking_pay_path(booking.id), class: 'btn btn-success btn-xs', method: :put
    else
    end
  end

  def cal_prices(booking)
    booking.total_payed
  end

  def get_incomes(bookings)
    incomes = 0
    bookings.each do |booking|
      incomes = incomes + cal_prices(booking) + booking.total_services_payed
    end
    incomes
  end

  def get_incomes_services(booking)
    service_incomes = 0
    booking.each do |booking|
      service_incomes = service_incomes + booking.total_services_payed
    end
    service_incomes
  end
end

app/helpers/cms/customers_helper.rb
module Cms::CustomersHelper
end

app/helpers/cms/employees_helper.rb
module Cms::EmployeesHelper
end

app/helpers/cms/image_room_tops_helper.rb
module Cms::ImageRoomTopsHelper
end

app/views/layouts/cms/application.html.erb
<head>
  <title>FinalProjectSch</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= include_gon(:init => true) %>
<%= Gon::Base.render_data({})  %>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<body class="home">
  <% unless requestlogin? %>
  <div class="container-fluid display-table">
    <div class="row display-table-row">
      <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box fix-size" id="navigation">
        <div class="logo">
          <img src="http://jskrishna.com/work/merkury/images/circle-logo.png" alt="merkery_logo" class="visible-xs visible-sm circle-logo">
          </a>
        </div>

          <div class="navi">
            <ul>
              <li class="active"><a href="/cms"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
              <% if  current_user.user_type == 'Admin' %>
              <li><a href="/cms/top_images"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Top Images</span></a></li>
              <li><a href="/cms/top_image_chooses"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Headline Images</span></a></li>
              <li><a href="/cms/image_room_tops"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Top Room Images</span></a></li>
              <li><a href="/cms/allow_ip_addresses"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Allow IP</span></a></li>
              <li><a href="/cms/users"><i class="fa fa-user" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Users</span></a></li>
              <li><a href="/cms/employees"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Employee</span></a></li>
              <li><a href="/cms/services"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Services</span></a></li>
              <% end %>
              <li><a href="/cms/customers"><i class="fa fa-tasks" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Customer</span></a></li>
              <li><a href="/cms/rooms"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Rooms</span></a></li>
              <li><a href="/cms/all_rooms/bookings"><i class="fa fa-bar-chart" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Rooms Schedule</span></a></li>
              <li><a href="/cms/bookings"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Bookings</span></a></li>
              <li><a href="/cms/booking_services"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Booking Services</span></a></li>
              <li><a href="/cms//bookings_services_watting"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Booking Services Waitting</span></a></li>
              <li><a href="/cms//watting_bookings"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Waitting Booking</span></a></li>
              <li><a href="/cms/revenues"><i class="fa fa-calendar" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Revenues</span></a></li>
              <!-- <li><a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li> -->
            </ul>
          </div>
      </div>
      <div class="col-md-10 col-sm-11 display-table-cell v-align">
        <!--<button type="button" class="slide-toggle">Slide Toggle</button> -->
        <div class="row">
          <header style="margin-bottom: 30px">
            <div class="col-md-7">
              <nav class="navbar-default pull-left">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  </button>
                </div>
              </nav>
              <!-- <div class="search hidden-xs hidden-sm">
                <input type="text" placeholder="Search" id="search">
                </div> -->
            </div>
            <div class="col-md-5">
              <div class="header-rightside">
                <ul class="list-inline header-top pull-right">
                  <!-- <li class="hidden-xs"><a href="#" class="add-project" data-toggle="modal" data-target="#add_project">Add Project</a></li> -->
                  <!-- <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li> -->
                  <!-- <li>
                    <a href="#" class="icon-info">
                    <i class="fa fa-bell" aria-hidden="true"></i>
                    <span class="label label-primary">3</span>
                    </a>
                  </li> -->
                  <div class="col-md-5">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <%= user_avartar current_user %>
                      <b class="caret"></b></a>
                      <ul class="dropdown-menu">
                        <li>
                          <div class="navbar-content">
                            <span><%= current_user_type.name %></span>
                            <p class="text-muted small">
                              <%= current_user.email %>
                            </p>
                            <div class="divider">
                            </div>
                            <%= link_to("View Profile", cms_user_path(current_user.id), class: "view btn-sm active") %>
                          </div>
                        </li>
                      </ul>
                    </li>
                  </div>
                  <div class="col-md-5">
                  <a href="<%=cms_logout_path%>" data-method="delete"><i class="fa fa-sign-out"></i>Logout</a>
                  </div>
                </ul>
              </div>
            </div>
          </header>
        </div>
        <div class="user-dashboard">
        <% end %>
        <div class="" style="">
          <%= yield %>
        </div>

<% unless requestlogin? %>
        </div>
      </div>
    </div>
  </div>
  <!-- Modal -->
  <div id="add_project" class="modal fade" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header login-header">
          <button type="button" class="close" data-dismiss="modal">×</button>
          <h4 class="modal-title">Add Project</h4>
        </div>
        <div class="modal-body">
          <input type="text" placeholder="Project Title" name="name">
          <input type="text" placeholder="Post of Post" name="mail">
          <input type="text" placeholder="Author" name="passsword">
          <textarea placeholder="Desicrption"></textarea>
        </div>
        <div class="modal-footer">
          <button type="button" class="cancel" data-dismiss="modal">Close</button>
          <button type="button" class="add-project" data-dismiss="modal">Save</button>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</body>
<style type="text/css">
  .fix-size {
    /*min-width:100px;*/
    /*max-width: 100px;*/
    /*width: 100px;*/
    font-family: initial;
  }
</style>