config/routes.rb
Rails.application.routes.draw do
  get 'paypal/checkout' => 'bookings#paypal_checkout'
  get 'bookings/paypal' => 'bookings#payment_save', as: :payment_save
  namespace :cms do
    get '/watting_bookings' => 'bookings#watting_bookings', as: :watting_bookings
    resources :allow_ip_addresses
    post '/allow_ip_addresses' => 'allow_ip_addresses#create', as: :create_allow_ip
    resources :image_room_tops, only: [:index, :update]
    put '/cms/update_image_room_tops' => 'image_room_tops#update', as: :update_image_room_tops
    resources :room_cannot_chooses
    root 'sessions#new'
    resources :services
    resources :bookings do
      resources :booking_services
    end
    get '/booking_services' => 'booking_services#index', as: :all_booking_services
    delete 'room_cannot_chooses/all/delete_all' => 'room_cannot_chooses#destroy_all', as: :room_cannot_chooses_all
    post '/bookings_services/:id' => 'booking_services#update', as: :update_booking_services
    resources :users
    resources :sessions
    resources :rooms
    resources :customers
    resources :top_images
    get 'histories/bookings' => 'bookings#history_index'
    get 'histories/bookings/:id' => 'bookings#histories'
    get 'bookings/:id/bill' => 'bookings#bill', as: :room_bill
    get 'csv_bill', to: 'bookings#csv_bills', as: :foo_export
    get 'customers/:id/bookings' => 'customers#bookings'
    get 'top_image_chooses' => 'top_images#edit_top_image_chooseds'
    put 'top_images_chooses' => 'top_images#update_top_image_chooses', as: :update_top_image_chooses
    get 'allrooms/bookings' => 'rooms#all_bookings'
    get 'rooms/:id/bookings' => 'rooms#bookings'
    get 'bookings/:id/new_services' => 'bookings#new_services', as: :booking_new_services
    post 'bookings/:booking_id/create_services/:service_id' => 'bookings#create_services', as: :booking_services
    put 'bookings/:booking_id/services' => 'booking_services#paid_all', as: :paid_all_services
    get 'all_rooms/bookings' => 'rooms#index_bookings', as: :bookings_all_rooms
    put '/booking/:id/booking_pay' => 'bookings#pay', as: :booking_pay
    get '/admin_find_rooms' => 'rooms#admin_find', as: :admin_find_rooms
    get '/employee_find_rooms' => 'rooms#employee_find_rooms', as: :employee_find_rooms
    get '/bookings_services_watting' => 'booking_services#waitting', as: :booking_services_waitting
    resources :employees
    post 'users/:id/changepassword' => 'users#changepassword', as: :changepassword
    post 'users/:id/update_avatar' => 'users#update_avatar', as: :update_avatar
    delete 'sessions#logout' => 'sessions#account_logout_out', as: :logout
    put 'booking_services/chooseds/pay' => 'booking_services#pay_chooseds', as: :booking_services_pay_chooseds
    put 'booking_services/invoice' => 'booking_services#invoice', as: :booking_services_invoice
    put 'bookings_invoice/:id' => 'bookings#invoice', as: :booking_invoice
    resources :revenues
  end

    get 'index' => 'homepages#index'
    get '/homepages/event' => 'homepages#event', as: :home_event
    resources :bookings, only: %w[new create show]
    resources :rooms, only: %w[show index]
    resources :customers
    root 'homepages#home'
    get '/booking/verify/success' => 'booking_verifies#success'
    get 'bookings/:id/watting_verify' => 'booking_verifies#watting_verify', as: :booking_watting_verify
    resources :booking_verifies, only: :edit
    post 'create_booking_with_payment' => 'bookings#create_booking_with_payment', as: :create_booking_with_payment
end

app/controllers/cms/allow_ip_addresses_controller.rb
class Cms::AllowIpAddressesController < Cms::ApplicationController
  before_action :check_admin
  def new
    @allow_ip_address = AllowAddressIp.new
  end

  def create
    AllowAddressIp.create allow_ip_address_params
    redirect_to cms_allow_ip_addresses_url
  end

  def destroy
    AllowAddressIp.find(params[:id]).delete
    redirect_to cms_allow_ip_addresses_url
  end

  def allow_ip_address_params
    params.require(:allow_address_ip).permit(:ip_address)
  end
end

app/controllers/cms/application_controller.rb
class Cms::ApplicationController < ApplicationController
  before_filter :block_ip_addresses
  before_action :check_if_valid_user_login
  def check_if_valid_user_login
    # it would be improve in future
    if controller_name != 'sessions'
      redirect_to cms_root_url if current_user.blank? || (current_user.user_type != 'Admin' && current_user.user_type != 'Employee')
    end
  end

  def block_ip_addresses
    allow_ip_addresses = AllowAddressIp.pluck(:ip_address)
    head :unauthorized if allow_ip_addresses.exclude?(current_ip_address)
  end

  def current_ip_address
    request.env['HTTP_X_REAL_IP'] || request.env['REMOTE_ADDR']
  end

  def check_admin
    redirect_to cms_root_path if current_user.user_type != 'Admin'
  end

  def service_prices booking
    total_prices = 0
    booking_services = BookingService.where(booking_id: booking.id, pay: :paid).where.not(status: :cancel)
    booking_services.each do |booking_service|
      total_prices = total_prices + booking_service.number*booking_service.price
    end
    total_prices
  end

  def get_date_incomes_date start_date
    dates = []
    start_date = Time.zone.now if start_date.blank?
    dates << (start_date.to_date - 2.year).strftime('%Y')
    dates << (start_date.to_date - 1.year).strftime('%Y')
    dates << start_date.to_date.strftime('%Y')
    dates
  end
end

app/controllers/cms/booking_services_controller.rb
class Cms::BookingServicesController < Cms::ApplicationController
  def new
    @booking_service = BookingService.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
  end

  def index
    @booking_services = BookingService.all
    @booking_services = @booking_services.order(:created_at).includes({booking: :room}, :service).page(params[:page]).per(10)
  end

  def update
    @booking_service = BookingService.find(params[:id])
    if booking_service_params[:commit].present?
      @booking_service.booked if params[:commit] == 'booked' && @booking_service.may_booked?
      @booking_service.cancel if params[:commit] == 'cancel' && @booking_service.may_cancel?
      @booking_service.paid   if params[:commit] == 'paid'   && @booking_service.may_paid?
      @booking_service.save
      redirect_to cms_booking_new_services_url(@booking_service.booking_id)
    end
  end

  def waitting
    @booking_services = BookingService.where(status: :watting).order(time: :asc).includes({booking: :room}, :service).page(params[:page]).per(10)
    render :index
  end

  def paid_all
    BookingService.paid_all(params[:booking_id])
    redirect_to cms_booking_new_services_url(params[:booking_id])
  end

  def pay_chooseds
    BookingService.where(id: params[:booking_service_ids]).update_all(pay: :paid)
    redirect_to cms_booking_new_services_path(params[:booking_id])
  end

  def invoice
    booking_services = BookingService.where(id: params['booking_service_ids'])
    if booking_services.present?
      items = []
      totlal_prices = 0
      booking_services.each do |booking_service|
        service = booking_service.service
        amount_after_tax = booking_service.price*booking_service.number
        item = InvoicePrinter::Document::Item.new(
          name: service.name,
          quantity: booking_service.number,
          price: booking_service.price*85/100,
          amount: '$ ' + (amount_after_tax*85/100).to_s
        )
        totlal_prices = totlal_prices + amount_after_tax
        items<<item
      end
      booking = booking_services.first.booking
      customer = booking.customer

      invoice = InvoicePrinter::Document.new(
        number: booking.id,
        provider_name: 'My Hotel',
        provider_tax_id: '56565656',
        provider_tax_id2: '465454',
        provider_street: 'Cua Dai',
        provider_street_number: '1',
        provider_city: 'Hoi An',
        purchaser_name: customer.name,
        purchaser_street: customer.street,
        purchaser_street_number: customer.number_street,
        purchaser_city: customer.city,
        purchaser_postcode: customer.postcode,
        due_date: (Time.zone.now + 7.hour).strftime('%Y-%m-%d %I:%M:%S %p'),
        subtotal: totlal_prices*85/100,
        tax: totlal_prices*10/100,
        tax2: totlal_prices*5/100,
        total: '$ ' + totlal_prices.to_s,
        items: items,
        note: 'A note...'
      )

      respond_to do |format|
        format.pdf {
          @pdf = InvoicePrinter.render(
            document: invoice
          )
          send_data @pdf, type: 'application/pdf', disposition: 'inline'
        }
      end
    else
      redirect_to cms_booking_new_services_path(params[:booking_id])
    end
  end

  def edit
    @booking_service = BookingService.find(params[:id])
  end

  def destroy
    BookingService.find(params[:id]).delete
  end

  def booking_service_params
    params.permit(:commit)
  end
end

app/controllers/cms/customers_controller.rb
class Cms::CustomersController < Cms::ApplicationController
  def index
    @customers = Customer.all
    @customers = @customers.where(email: params[:email]) if params[:email].present?
    @customers = @customers.where(country: params[:country]) if params[:country].present?
    @customers = @customers.where(postcode: params[:postcode]) if params[:postcode].present?
    @customers = @customers.page(params[:page]).per(25)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def bookings
    @customer = Customer.find(params[:id])
    @bookings = @customer.bookings.order(:created_at).page(params[:page]).per(10)
  end
end

app/controllers/cms/employees_controller.rb
class Cms::EmployeesController < Cms::ApplicationController
  def index
    @employees = Employee.all
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/cms/image_room_tops_controller.rb
class Cms::ImageRoomTopsController < Cms::ApplicationController
  before_action :init_record, :check_valid_params, only: :update

  def index
    @image_room_tops = ImageRoomTop.order(:image_room_top_number).all
  end

  def update
    if flash[:errors].blank?
      ImageRoomTop.update_rooms(image_room_top_params)
    end
    redirect_to cms_image_room_tops_url
  end

  def init_record
    ImageRoomTop.init_record
  end

  def check_valid_params
    flash[:errors] = ImageRoomTop.check_valid_params image_room_top_params
  end

  def image_room_top_params
    params.require(:image_room_tops).map {|a| a.permit(:image_room_top_number, :room_id)}
  end
end

app/controllers/cms/revenues_controller.rb
class Cms::RevenuesController < Cms::ApplicationController
  def index
    current_month = Time.zone.now.month
    current_year = Time.zone.now.year
    @dates_data = get_date_incomes_date(params['start_date'])
    @last_in_comes = Booking.get_last_in_comes(params['start_date'])
    @current_in_comes = Booking.get_current_in_comes(params['start_date'])
  end
end

app/controllers/cms/room_cannot_chooses_controller.rb
class Cms::RoomCannotChoosesController < Cms::ApplicationController
  before_action :check_valid_params, only: :create
  def update
  end

  def create
    @room_cannot_choose = RoomCannotChoose.new room_params
    if flash[:errors].blank?
      @room_cannot_choose.save
      flash[:success] = "Create success"
      redirect_to cms_room_cannot_chooses_url
    else
      @room_cannot_chooses = RoomCannotChoose.all
      render :index
    end
  end

  def index
    @room_cannot_chooses = RoomCannotChoose.all
  end

  def destroy
    RoomCannotChoose.find(params[:id]).delete
    redirect_to cms_room_cannot_chooses_url
  end

  def destroy_all
    RoomCannotChoose.delete_all
    redirect_to cms_room_cannot_chooses_url
  end

  def check_valid_params
    flash[:errors] = RoomCannotChoose.check_valid_params(room_params)
  end

  def room_params
    params.require(:room).permit(:room_id, :from_date, :to_date)
  end
end

app/controllers/cms/rooms_controller.rb
class Cms::RoomsController < Cms::ApplicationController
  before_action :check_admin, only:[:new, :create, :edit, :update, :destroy]
  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to cms_rooms_path(id: @room.id)
      flash[:success] = "New Room was created"
    else
      render :new
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update_attributes(room_params)
      redirect_to cms_rooms_path(id: @room.id)
      flash[:success] = "Update success"
    else
      redirect_to cms_rooms_path
      flash[:error] = "update fail"
    end
  end

  def show
    @room = Room.find(params[:id])
  end

  def index
    if params[:check_in].present? && params[:check_out].present? || params[:booking_edit].present?
      @rooms = Room.get_emptys(params[:check_in], params[:check_out])      if params[:empty].present? || params[:booking_edit].present?
      @rooms = Room.get_are_usings(params[:check_in], params[:check_out])  if params[:in_use].present?
    else
      @rooms = Room.all
    end
    if params[:price].present?
      @rooms = @rooms.order(:price)                              if params[:price] == 1
      @rooms = @rooms.order(price: :desc)                        if params[:price] == -1
    end
    @rooms = @rooms.where("adults > ?", params[:adults])         if params[:adults].present?
    @rooms = @rooms.where("childrens > ?", params[:childrens]) if params[:childrens].present?
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def admin_find
    @rooms = Room.where(name: params[:name])
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    @rooms = @rooms.page(params[:page]).per(10)
    render 'index'
  end

  def employee_find_rooms
    @rooms = Room.get_emptys(params[:check_in], params[:check_out])
    @rooms = @rooms.where("adults >= ?", params[:adults]) if params[:adults].present?
    @rooms = @rooms.where("childrens >= ?", params[:childrens]) if params[:childrens].present?
    @number = @rooms.count
    @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    render 'index'
  end

  def bookings
    @room = Room.find(params[:id])
    @bookings = @room.bookings.where("status != ? AND verified IS ?", 'watting', true)
  end

  def index_bookings
    if params[:check_in].present? && params[:check_out].present?
      @rooms = Room.get_emptys(params[:check_in], params[:check_out])
    else
      @rooms = Room.all
    end
    @rooms = @rooms.where("adults > ?", params[:adults])         if params[:adults].present? && @rooms.present?
    @rooms = @rooms.where("childrens > ?", params[:childrens]) if params[:childrens].present? && @rooms.present?
    @rooms = @rooms.includes(:bookings) if @rooms.present?
    # @rooms = @rooms.order(created_at: :desc).page(params[:page]).per(10)
    # @rooms = Room.all.includes(:bookings)
  end

  def all_bookings
    @rooms = Room.includes(:bookings).all
  end

  def destroy
    room = Room.find(params[:id])
    if room.destroy
      redirect_to cms_rooms_path
    end
  end

  private

    def room_params
      params.require(:room).permit(:id, :name, :room_type, :adults, :childrens, :price, :room_icon)
    end
end

app/controllers/cms/sessions_controller.rb
class Cms::SessionsController < Cms::ApplicationController
  def new
  end

  def create
    user = User.find_by(email: login_params[:email])
    if user.present? && user.password == login_params[:password]
      init_session(user)
      redirect_to cms_root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to cms_root_path
  end

  def account_logout_out
    logout
    redirect_to cms_root_path
  end

  def login_params
    params.permit(:email, :password)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def new
  end
end

app/helpers/cms/allow_ip_addresses_helper.rb
module Cms::AllowIpAddressesHelper
end

app/helpers/cms/booking_services_helper.rb
module Cms::BookingServicesHelper
  STATUS_COLOR = {'watting'   => '#00FFFF',
                  'booked'  => '#00FF00',
                  'cancel' => '#FF4500'
                  }

  def may_pay_all? booking_id
    booking_service = BookingService.where(booking_id: booking_id, pay: 'unpaid').limit(1)
    booking_service.present? ? true : false
  end
end

app/helpers/cms/bookings_helper.rb
module Cms::BookingsHelper
  STATUS_COLOR = {  'watting'  => 'yellow',
                    'cancel'   => '#f00',
                    'accepted' => '#48D1CC',
                    'in_use'   => '#0f0',
                    'finished' => '#FFA500'
                    }.freeze
  def pay_link_to booking
    total_price = (((@booking.check_out - @booking.check_in)/1.day.to_i + 1).to_i)*(@booking.price.to_i)
    if booking.total_payed == nil || booking.total_payed < total_price
      link_to 'paid', cms_booking_pay_path(booking.id), class: 'btn btn-success btn-xs', method: :put
    elsif booking.total_payed > total_price
      link_to 'change', cms_booking_pay_path(booking.id), class: 'btn btn-success btn-xs', method: :put
    else
    end
  end

  def cal_prices(booking)
    booking.total_payed
  end

  def get_incomes(bookings)
    incomes = 0
    bookings.each do |booking|
      incomes = incomes + cal_prices(booking) + booking.total_services_payed
    end
    incomes
  end

  def get_incomes_services(booking)
    service_incomes = 0
    booking.each do |booking|
      service_incomes = service_incomes + booking.total_services_payed
    end
    service_incomes
  end
end

app/helpers/cms/customers_helper.rb
module Cms::CustomersHelper
end

app/views/cms/customers/_form_find.html.erb
<form class="form-horizontal" action="/cms/customers">
<fieldset>

<div class="form-group">
  <label class="col-md-1 control-label" for="location">Email</label>
  <div class="col-md-2">
  <input id="location" name="email" value="<%=params[:email]%>" type="text" placeholder="Email" class="form-control input-md">
  </div>
  <label class="col-md-1 control-label" for="location">Country</label>
  <div class="col-md-2">
  <input id="location" name="country" value="<%=params[:country]%>" type="text" placeholder="Country" class="form-control input-md">
  </div>
  <label class="col-md-1 control-label" for="location">Postcode</label>
  <div class="col-md-2">
  <input id="location" name="postcode" value="<%=params[:postcode]%>" type="text" placeholder="Postcode" class="form-control input-md">
  </div>
  <label class="col-md-1 control-label" for="submit"></label>
  <div class="col-md-1">
    <button id= "submit" name="submit" class="btn btn-primary">Search</button>
  </div>
</div>

</fieldset>
</form>

app/views/cms/customers/bookings.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h4>Bookings of customer email <%=@customer.email%></h4>
      <div class="table-responsive">
        <table id="mytable" class="table table-bordred table-striped">
          <thead>
            <th>Id</th>
            <th>Name</th>
            <th>phone</th>
            <th>Country</th>
            <th>Room</th>
            <th>Check in</th>
            <th>Check out</th>
            <th>Adults</th>
            <th>Childrens</th>
            <th>Status</th>
            <th>Exepter</th>
            <th>Edit</th>
            <th>Delete</th>
          </thead>
          <tbody>
            <% @bookings.each do |booking| %>
            <% customer = booking.customer %>
            <tr class = "closesst1">
              <td><%= booking.id %></td>
              <td class="name1"><%= customer.name %></td>
              <td><%= customer.phonenumber %></td>
              <td><%= customer.country %></td>
              <td><%= booking.room.name%></td>
              <td><%= booking.check_in.strftime("%Y/%m/%d") %></td>
              <td><%= booking.check_out.strftime("%Y/%m/%d") %></td>
              <td><%= booking.adults %></td>
              <td><%= booking.childrens %></td>
              <td><%= booking.status%></td>
              <td><%= booking.user.username if booking.user.present? %></td>
              <td>
                <p data-placement="top" data-toggle="tooltip" title="Edit">
                  <button onclick="location.href='/cms/bookings/<%=booking.id%>/edit';" class="btn btn-primary btn-xs modalpop" data-title="Edit" >
                    <span class="glyphicon glyphicon-pencil">
                <div class = "a" value="a"></div>
                </span>
                </button
                  ></p>
              </td>
              <td>
                <p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="clearfix"></div>
        <%= paginate @bookings %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="edit" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></button>
        <h4 class="modal-title custom_align" id="Heading">Delete this entry</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-danger"><span class="glyphicon glyphicon-warning-sign"></span> Are you sure you want to delete this Record?</div>
      </div>
      <div class="modal-footer ">
        <button type="button" class="btn btn-success" ><span class="glyphicon glyphicon-ok-sign"></span> Yes</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> No</button>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>

app/views/cms/customers/index.html.erb
<!-- <div class="container"> -->
  <!-- <div class="row"> -->
    <!-- <div class="col-md-12"> -->
      <h1 style="text-align: center;">Customers</h1>
      <div style="text-align: center;">
      <%= render 'form_find' %>
      </div>
      <div class="table-responsive">
        <table id="mytable" class="table table-bordred table-striped">
          <thead>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Country</th>
            <th>City</th>
            <th>Street</th>
            <th>Number Street</th>
            <!-- <th>Current booking</th> -->
            <th>Detail</th>
            <th>Edit</th>
            <th>Delete</th>
          </thead>
          <tbody>
            <% @customers.each do |customer| %>
            <tr class = "closesst1">
              <td><a href="/cms/customers/<%=customer.id%>"><%=customer.id%></a></td>
              <td><%=customer.name%></td>
              <td><%=customer.email%></td>
              <td><%=customer.phonenumber%></td>
              <td><%=Country[customer.country].name%></td>
              <td><%=customer.city%></td>
              <td><%=customer.street%></td>
              <td><%=customer.number_street%></td>
              <td><%= link_to("detail", cms_customer_path(customer.id)) %></td>
              <td>
                <p data-placement="top" data-toggle="tooltip" title="Edit">
                  <button onclick="location.href='customers/<%=customer.id%>/edit';" class="btn btn-primary btn-xs modalpop" data-title="Edit" >
                    <span class="glyphicon glyphicon-pencil">
                <div class = "a" value="a"></div>
                </span>
                </button
                  ></p>
              </td>
              <td>
                <p data-placement="top" data-toggle="tooltip" title="Delete"><button class="btn btn-danger btn-xs" data-title="Delete" data-toggle="modal" data-target="#delete" ><span class="glyphicon glyphicon-trash"></span></button></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <%= paginate @customers, window: 2, outer_window: 1 %>
        <div class="clearfix"></div>
        <%= %>
      </div>
    <!-- </div> -->
  <!-- </div> -->
<!-- </div> -->

app/views/cms/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-9" >
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-title">Sheena Shrestha</h3>
        </div>
        <div class="panel-body">
          <div class="row">
            <!-- <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div> -->
            <!--<div class="col-xs-10 col-sm-10 hidden-md hidden-lg"> <br>
              <dl>
                <dt>DEPARTMENT:</dt>
                <dd>Administrator</dd>
                <dt>HIRE DATE</dt>
                <dd>11/12/2013</dd>
                <dt>DATE OF BIRTH</dt>
                   <dd>11/12/2013</dd>
                <dt>GENDER</dt>
                <dd>Male</dd>
              </dl>
              </div>-->
            <div class=" col-md-9 col-lg-9 ">
              <table class="table table-user-information">
                <tbody>
                  <tr>
                    <td>name:</td>
                    <td><%=@customer.name%></td>
                  </tr>
                  <tr>
                    <td>Email:</td>
                    <td><%=@customer.email %></td>
                  </tr>
                  <tr>
                    <td>Phone Number</td>
                    <td><%=@customer.phonenumber%></td>
                  </tr>
                  <tr>
                  <tr>
                    <td>Country</td>
                    <td><%=@customer.country%></td>
                  </tr>
                  <tr>
                    <td>Street</td>
                    <td><%=@customer.street%></td>
                  </tr>
                  <tr>
                    <td>Number Street</td>
                    <td><%=@customer.number_street%></a></td>
                  </tr>
                  <tr>
                    <td>City</td>
                    <td><%=@customer.city%></td>
                  </tr>
                  <tr>
                    <td>Postcode</td>
                    <td><%=@customer.postcode%></td>
                  </tr>
                  <tr>
                    <td>Bookings</td>
                    <td><a href="/cms/customers/<%=@customer.id%>/bookings">Bookings</a></td>
                  </tr>
                </tbody>
              </table>
              <!-- <a href="#" class="btn btn-primary">My Sales Performance</a>
              <a href="#" class="btn btn-primary">Team Sales Performance</a> -->
            </div>
          </div>
        </div>
        <!-- <div class="panel-footer">
          <a data-original-title="Broadcast Message" data-toggle="tooltip" type="button" class="btn btn-sm btn-primary"><i class="glyphicon glyphicon-envelope"></i></a>
          <span class="pull-right">
          <a href="edit.html" data-original-title="Edit this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a>
          <a data-original-title="Remove this user" data-toggle="tooltip" type="button" class="btn btn-sm btn-danger"><i class="glyphicon glyphicon-remove"></i></a>
          </span>
        </div> -->
      </div>
    </div>
  </div>
</div>
<style type="text/css">
  .user-row {
  margin-bottom: 14px;
  }
  .user-row:last-child {
  margin-bottom: 0;
  }
  .dropdown-user {
  margin: 13px 0;
  padding: 5px;
  height: 100%;
  }
  .dropdown-user:hover {
  cursor: pointer;
  }
  .table-user-information > tbody > tr {
  border-top: 1px solid rgb(221, 221, 221);
  }
  .table-user-information > tbody > tr:first-child {
  border-top: 0;
  }
  .table-user-information > tbody > tr > td {
  border-top: 0;
  }
  .toppad
  {margin-top:20px;
  }
</style>
<script type="text/javascript">
  $(document).ready(function() {
  var panels = $('.user-infos');
  var panelsButton = $('.dropdown-user');
  panels.hide();

  //Click dropdown
  panelsButton.click(function() {
    //get data-for attribute
    var dataFor = $(this).attr('data-for');
    var idFor = $(dataFor);

    //current button
    var currentButton = $(this);
    idFor.slideToggle(400, function() {
        //Completed slidetoggle
        if(idFor.is(':visible'))
        {
            currentButton.html('<i class="glyphicon glyphicon-chevron-up text-muted"></i>');
        }
        else
        {
            currentButton.html('<i class="glyphicon glyphicon-chevron-down text-muted"></i>');
        }
    })
  });


  $('[data-toggle="tooltip"]').tooltip();

  $('button').click(function(e) {
    e.preventDefault();
    alert("This is a demo.\n :-)");
  });
  });
</script>